### ISSUE TITLE
Transform Layer is not used

### ISSUE THREAD

**Issue by v-nhandt21** [xcmyz/FastVocoder#10]
Are there any reason that the transform layer is not used in default source code?

Have you found any inefficiency when using Transform?

**Comment by xcmyz** [comment]
> Are there any reason that the transform layer is not used in default source code?
> 
> Have you found any inefficiency when using Transform?

for ljspeech, you need transform layer, but for biaobei dataset, you dont need. You need experiment to decide whether add this layer.
