### ISSUE TITLE
Link to Basis-MelGAN paper?

### ISSUE THREAD

**Issue by seungwonpark** [xcmyz/FastVocoder#2]
Hi Zhengxi, congrats on your paper's acceptance on Interspeech 2021!

I got pretty interested in your paper while reading the abstract of Basis-MelGAN on the README, but I could not find any link to the paper. Though the Interspeech conference is only 2 months away, don't you have any plans on publishing the paper on arXiv in near future?

**Comment by xcmyz** [comment]
> Hi Zhengxi, congrats on your paper's acceptance on Interspeech 2021!
> 
> I got pretty interested in your paper while reading the abstract of Basis-MelGAN on the README, but I could not find any link to the paper. Though the Interspeech conference is only 2 months away, don't you have any plans on publishing the paper on arXiv in near future?

Thank you a lot, Seung-won. I will publish my paper on arXiv next week.

**Comment by seungwonpark** [comment]
Glad to hear that! Thank you.
