### ISSUE TITLE
why set the L=30 ?

### ISSUE THREAD

**Issue by yingfenging** [xcmyz/FastVocoder#4]
hello，I have some question， in the paper ，the shape of basis matrix  is [32, 256] , but in the code ,the shape is [30, 256] . 
And according to the function "overlap_and_add" , output_size = (frames - 1) * frame_step + frame_length,  if the L=30, I think it cannot match the real wave length ?
for example, hop_len=256,  mel.shape=[80, 140] , theoretically the output wave length is 140*256=35840. 
according to the code, the output wave length is 33600.

Thanks in advance.

**Comment by xcmyz** [comment]
> hello，I have some question， in the paper ，the shape of basis matrix is [32, 256] , but in the code ,the shape is [30, 256] .
> And according to the function "overlap_and_add" , output_size = (frames - 1) * frame_step + frame_length, if the L=30, I think it cannot match the real wave length ?
> for example, hop_len=256, mel.shape=[80, 140] , theoretically the output wave length is 140*256=35840.
> according to the code, the output wave length is 33600.
> 
> Thanks in advance.

Because of the different hop size.
`hop_size = upsample_rate_1 * upsample_rate_2 * (L / 2)`
Hope this helps.

**Comment by v-nhandt21** [comment]
With sample rate 22050, just set L to 32:
![image](https://user-images.githubusercontent.com/36092323/149705244-09cff17e-1c56-4470-a213-42997a3505ed.png)

**Comment by wizardk** [comment]
> With sample rate 22050, just set L to 32: ![image](https://user-images.githubusercontent.com/36092323/149705244-09cff17e-1c56-4470-a213-42997a3505ed.png)

What about the sample rate is 16000?
